cache:
  paths:
  - node_modules/
before_script:
  - npm-cli-login -u gisaia-team -p $pwd_npm -e tech@gisaia.com
  - npm install
lint:
  script:
  - npm run tslint
build:
  script:
  - npm run build-release

