sudo: required

language: node_js

node_js:
  - "8"

services:
  - docker

cache:
  directories:
  - node_modules/

before_script:
  - ./script/prebuild.sh

jobs:
  include:
    - script: npm run tslint
    - script: npm run build-release; mv dist/docs .
    - script: ./mkDocs.sh
